// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKG4tJD8SZ0OF9JSyyX2OlC5NDsyKokA',
    appId: '1:751482663594:web:3cd8447c3e364c3a2d56d3',
    messagingSenderId: '751482663594',
    projectId: 'parkinglot-3f855',
    authDomain: 'parkinglot-3f855.firebaseapp.com',
    storageBucket: 'parkinglot-3f855.appspot.com',
    measurementId: 'G-ZN3SLQ85DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfp329uxxaPrbvD5tRX32Ug1iqIBrfd8E',
    appId: '1:751482663594:android:d6a8bc5ddb4459a42d56d3',
    messagingSenderId: '751482663594',
    projectId: 'parkinglot-3f855',
    storageBucket: 'parkinglot-3f855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgo8nHrpNWjNMczLEnUVvr8CtpSrSCEc',
    appId: '1:751482663594:ios:7092575a407456ed2d56d3',
    messagingSenderId: '751482663594',
    projectId: 'parkinglot-3f855',
    storageBucket: 'parkinglot-3f855.appspot.com',
    iosClientId: '751482663594-0kd00g9p64o9jrdo3is5eb93cmgdglfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingLotVer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgo8nHrpNWjNMczLEnUVvr8CtpSrSCEc',
    appId: '1:751482663594:ios:7092575a407456ed2d56d3',
    messagingSenderId: '751482663594',
    projectId: 'parkinglot-3f855',
    storageBucket: 'parkinglot-3f855.appspot.com',
    iosClientId: '751482663594-0kd00g9p64o9jrdo3is5eb93cmgdglfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingLotVer1',
  );
}
